config/routes.rb
Nineninecats::Application.routes.draw do
  
  root :to => 'cats#index'
  match "login" => "sessions#new"
  match "dashboard" => "users#show"
  resources :cats do
    resources :cat_rental_requests, :path => "requests", :only => [:new, :create, :update]
  end
  resource :users, :only => [:new, :create, :show]
  resource :session, :except => [:edit, :show, :update, :index]

  

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  belongs_to :user

  has_many :cat_rental_requests, :dependent => :destroy

  validates :color, :inclusion => {:in => %w(blue red green),
    :message => "%{value} is not a valid color."}

  validates :name, :presence => true



end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :begin_date, :end_date, :status

  belongs_to :cat

  include ActiveModel::Validations
  validates_with RequestValidator

  def approve
    self.cat.cat_rental_requests.each do |request|
      next if request == self
      p request
      if self.begin_date < request.end_date &&
        self.end_date > request.begin_date
        request.status = 'denied'
        request.save!
      end
    end
    self.status = 'approved'

    self.save!
  end

  def deny
    self.status = 'denied'
    self.save!
  end


end

app/models/user.rb
require 'SecureRandom'

class User < ActiveRecord::Base
  attr_accessible :username, :password
  has_many :cats
  validates :username, :presence => true
  after_create :generate_token!

  def password= (password)
    self.password_hash = Digest::SHA2.base64digest(password)
  end

  def verify_password(password)
    self.password_hash == Digest::SHA2.base64digest(password)
  end

  def generate_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :find_current_user

  def current_user
    user = User.find_by_session_token(session[:session_token])
  end
  
  def find_current_user 
    @user = self.current_user
  end
  
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :find_cat

  def create
    request = @cat.cat_rental_requests.new(params[:cat_rental_request])
    if request.save
      redirect_to cat_path(@cat)
    else
      render :new
    end

  end

  def new
    render :new
  end

  def update
    if @user && @user == @cat.user
      @request = CatRentalRequest.find(params[:id])
      @request.approve if params[:cat_rental_request][:status] == "approved"
      @request.deny if params[:cat_rental_request][:status] == "denied"

      flash[:notices] ||= []
      flash[:notices] << "Request updated!"      
      
      redirect_to cat_path(@request.cat)
    else
      flash[:notices] ||= []
      flash[:notices] << "You cannot update this cat!"
      render :json => @request
    end

  end
  
  def find_cat
    @cat = Cat.find(params[:cat_id])
  end


end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def new
    render :new
  end

  def create
    @cat = Cat.new(params[:cat])
    if @cat.save
      render :show
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(params[:cat])
      render :show
    else
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user_found = User.find_by_username(params[:user][:username])
    
    if user_found.nil?
      render :json => {'error' => 'Incorrect username.'}
      return
    end

    if user_found.verify_password(params[:user][:password])
      session[:session_token] = user_found.generate_token!
      render :json => user_found
    else
      flash[:notices] ||= []
      flash[:notices] << "Go away, hacker."
      
      render :new
    end
  end

  def destroy
    user.session_token = nil 
    user.save! 
    
    session[:session_token] = nil 
    
    flash[:notices] ||= []
    flash[:notices] << "You have logged out!"
    
    redirect_to root_url 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    new_user = User.new(params[:user])
    if new_user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    if @user.nil?
      render :json => {"nil" => "empty page"}
    else
      render :profile
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<h2>Rent-a-cat!</h2>

<h3>Rental form for <%= @cat.name %></h3>

<form id="" action=<%= "/cats/#{@cat.id}/requests" %> method="post">

	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">

	<label for="birth_date">Day rental begins</label><br>
	<input type="date" name="cat_rental_request[begin_date]" value="" id="begin_date"><br>

	<label for="birth_date">Day Rental Ends</label><br>
	<input type="date" name="cat_rental_request[end_date]" value="" id="end_date"><br>

	<label for="Submit">Submit Cat</label>
	<input type="submit" name="Submit" value="Submit" id="Submit">

</form>

app/views/cats/edit.html.erb
<h2>Edit your Cat's Info</h2>

<form id="" method="post" action= <%= "/cats/#{@cat.id}" %> >
	<!-- You need to create a hidden method so that you can emulate a 'put' -->
	<input type="hidden" name="_method" value="put">
	
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">

	<label for="Name">Name</label>
	<input type="text" name="cat[name]" value=<%= "#{@cat.name}" %> id="Name"><br>

	<label for="age">age</label>
	<input type="text" name="cat[age]" value=<%= "#{@cat.age}" %> id="age"><br>

	<label for="birth_date">birth_date</label>
	<input type="date" name="cat[birth_date]" value=<%= "#{@cat.birth_date}" %> id="birth_date"><br>

	<label for="color">Color</label>
	<input type="text" name="cat[color]" value=<%= "#{@cat.color}" %> id="color"><br>

	<label for="gender">gender</label>
	<input type="text" name="cat[sex]" value=<%= "#{@cat.sex ? @cat.sex : 'blank' }" %> id="gender"><br>

	<label for="Submit">Submit Cat</label>
	<input type="submit" name="Submit" value="Submit" id="Submit">

</form>

app/views/cats/index.html.erb
<% @cats.each do |cat| %>
	<div>
		<h3><%= link_to "#{cat.name}", cat_path(cat) %></h3>
		<%= cat.age ? cat.age : 'unknown' %> years old<br>
		born: <%= cat.birth_date %><br>
		gender: <%= cat.sex ? cat.sex : "not given" %> <br>
		color: <%= cat.color %><br>
		<hr>
	</div>
<%end%>

app/views/cats/new.html.erb
<h2>Make a new cat</h2>

<form id="" action="/cats" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">
	<label for="Name">Name</label>
	<input type="text" name="cat[name]" value="" id="Name"><br>

	<label for="age">age</label>
	<input type="text" name="cat[age]" value="" id="age"><br>

	<label for="birth_date">birth_date</label>
	<input type="date" name="cat[birth_date]" value="" id="birth_date"><br>

	<label for="color">Color</label>
	<input type="text" name="cat[color]" value="" id="color"><br>

	<label for="gender">gender</label>
	<input type="text" name="cat[sex]" value="" id="gender"><br>

	<input type="hidden" name="cat[user_id]" value="<%= @user.id %>" id="owner"><br>

	<label for="Submit">Submit Cat</label>
	<input type="submit" name="Submit" value="Submit" id="Submit">

</form>

app/views/cats/show.html.erb
<h2>We Have Found Your Cat.</h2>

<div>
	<h3>catname: <%= @cat.name %></h3>
	<%= link_to "Edit Cat", edit_cat_path(@cat) %> <br><br>
	<%= @cat.age ? @cat.age : 'unknown' %> years old<br>
	born: <%= @cat.birth_date %><br>
	gender: <%= @cat.sex ? @cat.sex : "not given" %> <br>
	color: <%= @cat.color %><br>

	<h3>existing requests for <%= @cat.name %></h3>
	
		<%= "No outstanding requests. Meow" if @cat.cat_rental_requests.empty? %>	
		<% @cat.cat_rental_requests.order("begin_date").each do |rental| %>
		begin_date = <%= rental.begin_date %> <br>
		end_date = <%= rental.end_date %> <br>
		status = <%= rental.status %> <br>
		<% if @user && @user == @cat.user %>
			<% unless rental.status == 'approved' %>
				<b>Approve or Deny the Cat Request?</b>

				<form action=<%= "/cats/#{@cat.id}/requests/#{rental.id}" %> method="post">
					<input type="hidden" name="_method" value="put">
					<input type="hidden" name="cat_rental_request[status]" value="approved" id="cat_rental_request[status]">
					<input type="submit" name="Approve" value="approve" id="Approve">
				</form>

				<form action=<%= "/cats/#{@cat.id}/requests/#{rental.id}" %> method="post">
					<input type="hidden" name="_method" value="put">
					<input type="hidden" name="cat_rental_request[status]" value="deny" id="cat_rental_request[status]">
					<input type="submit" name="Deny" value="deny" id="deny">
				</form>
			<%end%>
		<% end %>
		<hr>
	<% end %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nineninecats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= @user ? "logged in as #{@user.username}" : "logged out"  %><br>
	<% flash[:notices].try(:each) do |msg| %>
		<%=msg %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h3>Create a User</h3>

<form id="" action="/users" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">
	<label for="username">username</label><input type="text" name="user[username]" value="" id="username">
	<label for="password">password</label><input type="text" name="user[password]" value="" id="password">
	<label for="Submit"></label><input type="submit" name="submit user" value="submit" id="">



</form>

app/views/users/profile.html.erb
<h3>User Dashboard page for <%= @user.username %></h3>

name: <%= @user.username %>